Repository creative-system-consultant/SISKOPv3, pull requests merged in 2024-03, with the labels that each got.

#58 FixApplyCalcDiv
  app/Http/Livewire/Page/Application/Dividend/ApplyDividend.php
Labels: bug

#59 EnhanceValidationCalcApplyDiv
  app/Http/Livewire/Page/Application/Dividend/ApplyDividend.php
Labels: enhancement

#60 Add Rules Min Amount
  app/Http/Livewire/Page/Application/Dividend/ApplyDividend.php
Labels: enhancement

#61 AddNewFields
  app/Models/SiskopFamily.php
  resources/views/livewire/page/executive/approval/membership/information/beneficiary.blade.php
Labels: enhancement

#62 FixError#61
  resources/views/livewire/page/executive/approval/membership/information/beneficiary.blade.php
Labels: bug

#65 RenameLableAddContribution
  app/Http/Livewire/Page/Application/ApplyContribution/ApplyContribution.php
  resources/views/livewire/page/application/apply-contribution/apply-contribution.blade.php
Labels: enhancement

#68 EnhanceRegis
  app/Http/Livewire/Auth/Register.php
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
  resources/views/livewire/auth/register.blade.php
Labels: enhancement

#69 Dividend Fixes
  app/Http/Livewire/Page/Application/Dividend/ApplyDividend.php
  resources/views/livewire/page/application/dividend/apply-dividend.blade.php
  resources/views/livewire/page/executive/approval/approval/dividend.blade.php
Labels: bug

#71 Change Guarantor Fixes
  app/Http/Livewire/Page/Application/ApplicationList/ChangeGuarantor.php
  app/Http/Livewire/Page/Application/ApplyChangeGuarantor/Index.php
  app/Models/GuarantorList.php
Labels: bug

#72 Approval Fixes
  app/Http/Livewire/Page/Executive/Approval/Approval/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
Labels: bug

#73 Guest and Application Minor Fixes
  app/Http/Livewire/Page/Dashboard/guest.php
  resources/views/livewire/page/application/membership/basicinfo.blade.php
Labels: bug

#76 Address Code
  app/Http/Livewire/Page/Admin/Coop/ClientCreate.php
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Checker.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Committee.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Maker.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Resolution.php
  app/Http/Livewire/Page/Profile/Profile.php
  app/Http/Middleware/CheckProfileCompletion.php
Labels: enhancement

#77 renamePopUp
  app/Http/Livewire/Page/Application/ApplySellExchangeShare/ApplySellExchangeShare.php
Labels: enhancement

#79 Profile Code Fixes
  app/Http/Livewire/Page/Profile/Profile.php
  resources/views/livewire/page/profile/profile.blade.php
Labels: bug

#80 Rename
  resources/views/livewire/auth/register.blade.php
Labels: enhancement

#83 fix issue #82
  app/Http/Livewire/Auth/Register.php
  app/Http/Livewire/Page/Dashboard/guest.php
  resources/views/layouts/sidebar/desktop.blade.php
Labels: bug

#84 showValues
  resources/views/livewire/page/executive/approval/approval/exchangeshare.blade.php
  resources/views/livewire/page/executive/approval/approval/specialaid.blade.php
Labels: enhancement

#85 FixClosedMembership
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
  resources/views/livewire/page/executive/approval/approval/closemembership.blade.php
Labels: bug, enhancement

#86 AdjustmentHeader
  resources/views/livewire/page/application/application-list/dividend.blade.php
Labels: enhancement

#89 Guarantor&ContributionFix
  app/Http/Livewire/Page/Application/ApplyContribution/ApplyContribution.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Approver.php
  app/Models/FmsMembership.php
  resources/views/livewire/page/application/apply-change-guarantor/index.blade.php
Labels: bug, enhancement

#90 ClosedMembership
  resources/views/livewire/page/application/apply-closed-membership/index.blade.php
Labels: enhancement

#92 fix issue #91
  app/Models/User.php
  resources/views/livewire/page/dashboard/guest.blade.php
Labels: enhancement

#94 Membership Finance Fix
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
  resources/views/livewire/page/application/membership/paymentinfo.blade.php
Labels: bug

#95 SpecialAids
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
  resources/views/livewire/page/executive/approval/approval/specialaid.blade.php
Labels: bug, enhancement

#96 HeaderTopbar
  app/Models/User.php
  resources/views/layouts/sidebar/topbar.blade.php
Labels: enhancement

#97 WithdrawalDividend
  app/Models/ApplyDividend.php
  resources/views/livewire/page/application/application-list/dividend.blade.php
Labels: bug

#99 fix new membership deduction share error
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
  resources/views/livewire/page/application/membership/new-membership.blade.php
Labels: bug

#100 update for installment
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
Labels: bug

#101 ClosedMembershipRemoveColumn
  resources/views/livewire/page/executive/approval/approval/closemembership.blade.php
Labels: enhancement

#103 fix issue #102
  app/Http/Livewire/Page/Executive/Approval/Approval/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Checker.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Committee.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Resolution.php
Labels: bug

#104 WithdrawalDiv
  resources/views/livewire/page/application/application-list/dividend.blade.php
Labels: bug, enhancement

#106 fix issue #105
  app/Http/Livewire/Page/Application/ApplyChangeGuarantor/Index.php
  resources/views/livewire/page/application/apply-change-guarantor/index.blade.php
  resources/views/livewire/page/executive/approval/approval/ChangeGuarantor.blade.php
Labels: bug

#107 add/WithdrawalCont
  resources/views/livewire/page/executive/approval/approval/contribution.blade.php
Labels: enhancement

#108 ammend change guarantor
  resources/views/livewire/page/executive/approval/approval/ChangeGuarantor.blade.php
Labels: bug

#109 ChangeModelRelationship
  app/Models/SiskopFamily.php
Labels: bug, enhancement

#110 ammend contibution validation
  app/Http/Livewire/Page/Executive/Approval/Approval/Checker.php
Labels: bug

#111 New Registered Client Error
  resources/views/layouts/sidebar/topbar.blade.php
Labels: bug

#113 Dividend Fixes
  app/Http/Livewire/Page/Application/Dividend/ApplyDividend.php
Labels: bug

#114 DividendWithdrawal
  app/Http/Livewire/Page/Executive/Approval/Approval/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
  resources/views/livewire/page/application/dividend/apply-dividend.blade.php
Labels: bug, enhancement

#115 DividendQuickFix
  app/Http/Livewire/Page/Application/Dividend/ApplyDividend.php
Labels: bug

#117 fix issue #116
  app/Http/Livewire/Page/Application/ApplicationList/ApplicationList.php
  app/Http/Livewire/Page/Application/ApplicationList/ChangeGuarantor.php
  app/Http/Livewire/Page/Application/ApplicationList/CloseMembership.php
  app/Http/Livewire/Page/Application/ApplicationList/Contribution.php
  app/Http/Livewire/Page/Application/ApplicationList/Dividend.php
  app/Http/Livewire/Page/Application/ApplicationList/ExchangeShare.php
  app/Http/Livewire/Page/Application/ApplicationList/Financing.php
  app/Http/Livewire/Page/Application/ApplicationList/Membership.php
  app/Http/Livewire/Page/Application/ApplicationList/SellShare.php
  app/Http/Livewire/Page/Application/ApplicationList/Share.php
  app/Http/Livewire/Page/Application/ApplicationList/SpecialAid.php
  app/Http/Livewire/Page/Application/ApplicationList/WithdrawalContribution.php
  resources/views/layouts/sidebar/desktop.blade.php
  resources/views/livewire/page/application/application-list/application-list.blade.php
  routes/web.php
Labels: enhancement

#118 Update Special Aid
  app/Http/Livewire/Page/Executive/Approval/Approval/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
  resources/views/livewire/page/executive/approval/approval/specialaid.blade.php
Labels: bug

#120 Membership Major Fixes
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Checker.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Committee.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Maker.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Resolution.php
  resources/views/livewire/page/application/dividend/apply-dividend.blade.php
  resources/views/livewire/page/executive/approval/membership/information/payment.blade.php
Labels: bug, enhancement

#121 FixRegister
  app/Http/Livewire/Page/Executive/Approval/Membership/Maker.php
  resources/views/livewire/page/executive/approval/membership/information/payment.blade.php
Labels: bug, enhancement

#122 ammend approval list
  app/Http/Livewire/Page/Application/ApplicationList/ChangeGuarantor.php
  app/Http/Livewire/Page/Application/ApplicationList/CloseMembership.php
  app/Http/Livewire/Page/Application/ApplicationList/Contribution.php
  app/Http/Livewire/Page/Application/ApplicationList/Dividend.php
  app/Http/Livewire/Page/Application/ApplicationList/ExchangeShare.php
  app/Http/Livewire/Page/Application/ApplicationList/Membership.php
  app/Http/Livewire/Page/Application/ApplicationList/SellShare.php
  app/Http/Livewire/Page/Application/ApplicationList/Share.php
  app/Http/Livewire/Page/Application/ApplicationList/SpecialAid.php
  app/Http/Livewire/Page/Application/ApplicationList/WithdrawalContribution.php
  resources/views/livewire/page/application/application-list/application-list.blade.php
  resources/views/livewire/page/application/application-list/changeguarantor.blade.php
  resources/views/livewire/page/application/application-list/close-membership.blade.php
  resources/views/livewire/page/application/application-list/contribution.blade.php
  resources/views/livewire/page/application/application-list/dividend.blade.php
  resources/views/livewire/page/application/application-list/exchangeshare.blade.php
  resources/views/livewire/page/application/application-list/membership.blade.php
  resources/views/livewire/page/application/application-list/sellshare.blade.php
  resources/views/livewire/page/application/application-list/share.blade.php
  resources/views/livewire/page/application/application-list/special-aid.blade.php
  resources/views/livewire/page/application/application-list/withdrawal-contribution.blade.php
Labels: enhancement

#124 add validation
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
Labels: bug

#125 fix continue apply membership
  app/Models/User.php
Labels: bug

#126 Membership Payment Fixes
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Maker.php
  resources/views/livewire/page/application/membership/paymentinfo.blade.php
  resources/views/livewire/page/executive/approval/membership/information/payment.blade.php
Labels: bug, enhancement

#127 ammend membership
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
Labels: bug

#128 Special Aid Fixes
  app/Http/Livewire/Page/Executive/Approval/Approval/Maker.php
Labels: bug

#129 Validation Hot Fix
  app/Http/Livewire/Page/Application/Membership/NewMembership.php
Labels: bug

#130 All Approver Share Display Fix
  app/Http/Livewire/Page/Executive/Approval/Membership/Approver.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Checker.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Committee.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Maker.php
  app/Http/Livewire/Page/Executive/Approval/Membership/Resolution.php
Labels: bug
